server:
  port: 8082

spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/gestion_bibliotecas
    username: postgres
    password: 123software
    pool:
      enabled: true
      initial-size: 5
      max-size: 20

logging:
  level:
    org:
      springframework:
        r2dbc: DEBUG

  webclient:
    base-url: http://localhost:8080
