spring.application.name=User_Library_Management
# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/gestion_bibliotecas
spring.datasource.username=postgres
spring.datasource.password=123software
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

